package tempo

import "core:fmt"
import "core:strings"

Generator :: struct {
    out:         strings.Builder,
    literal_buf: strings.Builder,
    indent:      int,
    runtime_pkg: string,
    // Scope tracking for capture analysis
    scope:       [dynamic]Scope_Var,
    // File hash for unique IDs across files
    file_hash:   string,
    // Current template name for scoped unique IDs
    current_template: string,
    // Unique ID counter within current template
    uid_counter: int,
}

// A variable in scope that can be captured
Scope_Var :: struct {
    name:  string,
    type_: string,  // Odin type as string
}

// Capture info for a slot
Capture :: struct {
    vars: []Scope_Var,
}

// Generate Odin code from parsed file
generate_file :: proc(file: ^File, runtime_pkg := "tempo") -> string {
    g := Generator{
        runtime_pkg = runtime_pkg,
    }
    strings.builder_init(&g.out)
    strings.builder_init(&g.literal_buf)

    emit_header(&g)
    emit_package(&g, file)
    emit_imports(&g, file)
    emit_decls(&g, file)

    return strings.to_string(g.out)
}

// Generate from segments (before full File is built)
generate_from_segments :: proc(segments: []Segment, filename := "", runtime_pkg := "tempo") -> string {
    g := Generator{
        runtime_pkg = runtime_pkg,
        file_hash   = hash_string(filename),
    }
    strings.builder_init(&g.out)
    strings.builder_init(&g.literal_buf)

    // Find package
    for seg in segments {
        if pkg, ok := seg.(Package_Segment); ok {
            emit_header(&g)
            gen_writeln(&g, "package %s", pkg.name)
            gen_writeln(&g, "")
            break
        }
    }

    // Collect and dedupe imports
    emit_deduped_imports(&g, segments)

    // Emit declarations
    for seg in segments {
        switch s in seg {
        case Odin_Segment:
            gen_writeln(&g, "%s", s.code)
            gen_writeln(&g, "")

        case Templ_Segment:
            template, ok := parse_template(s)
            if ok {
                emit_template(&g, template)
            }

        case CSS_Segment:
            emit_css(&g, s)

        case Script_Segment:
            emit_script(&g, s)

        case Package_Segment, Import_Segment:
            // Already handled
        }
    }

    return strings.to_string(g.out)
}

emit_header :: proc(g: ^Generator) {
    gen_writeln(g, "// Code generated by tempo - DO NOT EDIT.")
    gen_writeln(g, "")
}

emit_package :: proc(g: ^Generator, file: ^File) {
    gen_writeln(g, "package %s", file.package_.name)
    gen_writeln(g, "")
}

emit_imports :: proc(g: ^Generator, file: ^File) {
    gen_writeln(g, `import "core:strings"`)
    gen_writeln(g, `import templ "%s"`, g.runtime_pkg)

    for imp in file.imports {
        if alias, ok := imp.alias.?; ok {
            gen_writeln(g, `import %s "%s"`, alias, imp.path)
        } else {
            gen_writeln(g, `import "%s"`, imp.path)
        }
    }
    gen_writeln(g, "")
}

// Import info for deduplication
Import_Info :: struct {
    alias: string,  // Empty if no alias
    path:  string,
}

// Emit deduplicated imports from segments
emit_deduped_imports :: proc(g: ^Generator, segments: []Segment) {
    // Use a map to track seen import paths
    seen: map[string]bool
    defer delete(seen)

    imports: [dynamic]Import_Info
    defer delete(imports)

    // Always add core:strings
    seen["core:strings"] = true
    append(&imports, Import_Info{alias = "", path = "core:strings"})

    // Always add tempo runtime (unless user provides their own templ alias)
    has_templ_alias := false
    for seg in segments {
        if imp, ok := seg.(Import_Segment); ok {
            if info, parsed := parse_import_text(imp.text); parsed {
                if info.alias == "templ" {
                    has_templ_alias = true
                    break
                }
            }
        }
    }

    if !has_templ_alias {
        seen[g.runtime_pkg] = true
        append(&imports, Import_Info{alias = "templ", path = g.runtime_pkg})
    }

    // Collect user imports
    for seg in segments {
        if imp, ok := seg.(Import_Segment); ok {
            // Handle import groups: import ( ... )
            if strings.contains(imp.text, "(") {
                // Parse each import in the group
                parse_import_group(imp.text, &imports, &seen)
            } else {
                // Single import
                if info, parsed := parse_import_text(imp.text); parsed {
                    if !(info.path in seen) {
                        seen[info.path] = true
                        append(&imports, info)
                    }
                }
            }
        }
    }

    // Emit all imports
    for imp in imports {
        if imp.alias != "" {
            gen_writeln(g, `import %s "%s"`, imp.alias, imp.path)
        } else {
            gen_writeln(g, `import "%s"`, imp.path)
        }
    }
    gen_writeln(g, "")
}

// Parse a single import statement: import "path" or import alias "path"
parse_import_text :: proc(text: string) -> (Import_Info, bool) {
    trimmed := strings.trim_space(text)

    // Skip "import" keyword
    if !strings.has_prefix(trimmed, "import") {
        return {}, false
    }

    rest := strings.trim_space(trimmed[6:])

    // Skip if it's a group import (handled separately)
    if strings.has_prefix(rest, "(") {
        return {}, false
    }

    // Check for alias: import alias "path"
    if !strings.has_prefix(rest, "\"") {
        // Has alias
        space_idx := strings.index(rest, " ")
        if space_idx == -1 {
            return {}, false
        }

        alias := strings.trim_space(rest[:space_idx])
        path_part := strings.trim_space(rest[space_idx:])

        // Extract path from quotes
        if path, ok := extract_quoted_string(path_part); ok {
            return Import_Info{alias = alias, path = path}, true
        }
        return {}, false
    }

    // No alias: import "path"
    if path, ok := extract_quoted_string(rest); ok {
        return Import_Info{alias = "", path = path}, true
    }

    return {}, false
}

// Parse an import group: import ( "path1" \n alias "path2" ... )
parse_import_group :: proc(text: string, imports: ^[dynamic]Import_Info, seen: ^map[string]bool) {
    // Find content between ( and )
    open_idx := strings.index(text, "(")
    close_idx := strings.last_index(text, ")")

    if open_idx == -1 || close_idx == -1 || close_idx <= open_idx {
        return
    }

    content := text[open_idx+1:close_idx]
    lines := strings.split_lines(content)

    for line in lines {
        trimmed := strings.trim_space(line)
        if trimmed == "" {
            continue
        }

        // Parse: alias "path" or "path"
        if !strings.has_prefix(trimmed, "\"") {
            // Has alias
            space_idx := strings.index(trimmed, " ")
            if space_idx == -1 {
                continue
            }

            alias := strings.trim_space(trimmed[:space_idx])
            path_part := strings.trim_space(trimmed[space_idx:])

            if path, ok := extract_quoted_string(path_part); ok {
                if !(path in seen) {
                    seen[path] = true
                    append(imports, Import_Info{alias = alias, path = path})
                }
            }
        } else {
            // No alias
            if path, ok := extract_quoted_string(trimmed); ok {
                if !(path in seen) {
                    seen[path] = true
                    append(imports, Import_Info{alias = "", path = path})
                }
            }
        }
    }
}

// Extract string content from quoted string
extract_quoted_string :: proc(s: string) -> (string, bool) {
    trimmed := strings.trim_space(s)
    if len(trimmed) < 2 {
        return "", false
    }

    if trimmed[0] != '"' {
        return "", false
    }

    end_idx := strings.index(trimmed[1:], "\"")
    if end_idx == -1 {
        return "", false
    }

    return trimmed[1:end_idx+1], true
}

emit_decls :: proc(g: ^Generator, file: ^File) {
    for decl in file.decls {
        switch d in decl {
        case Template_Decl:
            emit_template(g, d)
        case CSS_Decl:
            // TODO
        case Script_Decl:
            // TODO
        case Odin_Decl:
            gen_writeln(g, "%s", d.code)
            gen_writeln(g, "")
        }
    }
}

// Template generation - takes value, not pointer
emit_template :: proc(g: ^Generator, t: Template_Decl) {
    params := extract_params(t.params)
    slot_names := collect_slot_names(t.body)

    // Set current template for scoped unique IDs
    g.current_template = t.name
    g.uid_counter = 0

    // Push template parameters onto scope
    scope_start := len(g.scope)
    for sv in parse_params(t.params) {
        append(&g.scope, sv)
    }

    // Build parameter list
    param_parts: [dynamic]string
    if params != "" {
        append(&param_parts, params)
    }

    // Add slot parameters (with data: rawptr for captures)
    for name in slot_names {
        if name == "" {
            append(&param_parts, "slot: proc(w: ^strings.Builder, data: rawptr) = nil")
            append(&param_parts, "slot_data: rawptr = nil")
        } else {
            append(&param_parts, fmt.tprintf("slot_%s: proc(w: ^strings.Builder, data: rawptr) = nil", name))
            append(&param_parts, fmt.tprintf("slot_%s_data: rawptr = nil", name))
        }
    }

    if len(param_parts) == 0 {
        gen_writeln(g, "%s :: proc(w: ^strings.Builder) {{", t.name)
    } else {
        gen_writeln(g, "%s :: proc(w: ^strings.Builder, %s) {{", t.name, strings.join(param_parts[:], ", "))
    }

    g.indent += 1
    emit_nodes(g, t.body)
    flush_literal(g)
    g.indent -= 1

    gen_writeln(g, "}}")
    gen_writeln(g, "")

    // Pop scope - shrink back to original size
    for len(g.scope) > scope_start {
        pop(&g.scope)
    }
}

// Collect all slot names used in a template body
collect_slot_names :: proc(nodes: []Node) -> []string {
    names: [dynamic]string
    has_default := false

    collect_from_nodes(nodes, &names, &has_default)

    // Add default slot if used
    if has_default {
        // Insert at beginning
        inject_at(&names, 0, "")
    }

    return names[:]
}

collect_from_nodes :: proc(nodes: []Node, names: ^[dynamic]string, has_default: ^bool) {
    for node in nodes {
        collect_from_node(node, names, has_default)
    }
}

collect_from_node :: proc(node: Node, names: ^[dynamic]string, has_default: ^bool) {
    switch n in node {
    case Slot:
        if name, ok := n.name.?; ok {
            // Named slot - add if not already present
            found := false
            for existing in names {
                if existing == name {
                    found = true
                    break
                }
            }
            if !found {
                append(names, name)
            }
        } else {
            // Default slot
            has_default^ = true
        }
    case Element:
        collect_from_nodes(n.children, names, has_default)
    case If_Node:
        collect_from_nodes(n.then_, names, has_default)
        for ei in n.else_ifs {
            collect_from_nodes(ei.then_, names, has_default)
        }
        collect_from_nodes(n.else_, names, has_default)
    case For_Node:
        collect_from_nodes(n.body, names, has_default)
    case Switch_Node:
        for c in n.cases {
            collect_from_nodes(c.body, names, has_default)
        }
    case Call:
        collect_from_nodes(n.default_slot, names, has_default)
        for ns in n.named_slots {
            collect_from_nodes(ns.body, names, has_default)
        }
    case Text, Whitespace, Expr, Raw_Expr, Odin_Block, Comment:
        // No slots
    }
}

// Extract params from "(name: string, age: int)" -> "name: string, age: int"
extract_params :: proc(params: string) -> string {
    trimmed := strings.trim_space(params)
    if trimmed == "()" || trimmed == "" {
        return ""
    }
    // Strip only the outer parens, not all parens (important for Maybe(T) etc)
    if len(trimmed) >= 2 && trimmed[0] == '(' && trimmed[len(trimmed)-1] == ')' {
        return strings.trim_space(trimmed[1:len(trimmed)-1])
    }
    return trimmed
}

// Parse params into scope variables: "(name: string, users: []User)" -> [{name, string}, {users, []User}]
parse_params :: proc(params: string) -> []Scope_Var {
    inner := extract_params(params)
    if inner == "" {
        return nil
    }

    vars: [dynamic]Scope_Var

    // Split by comma, handling nested brackets
    depth := 0
    start := 0
    for i := 0; i < len(inner); i += 1 {
        c := inner[i]
        switch c {
        case '(', '[', '{':
            depth += 1
        case ')', ']', '}':
            depth -= 1
        case ',':
            if depth == 0 {
                if sv, ok := parse_single_param(inner[start:i]); ok {
                    append(&vars, sv)
                }
                start = i + 1
            }
        }
    }
    // Last param
    if start < len(inner) {
        if sv, ok := parse_single_param(inner[start:]); ok {
            append(&vars, sv)
        }
    }

    return vars[:]
}

// Parse "name: string" into Scope_Var
parse_single_param :: proc(param: string) -> (Scope_Var, bool) {
    trimmed := strings.trim_space(param)
    if trimmed == "" {
        return {}, false
    }

    colon_idx := strings.index(trimmed, ":")
    if colon_idx == -1 {
        return {}, false
    }

    name := strings.trim_space(trimmed[:colon_idx])
    type_ := strings.trim_space(trimmed[colon_idx+1:])

    return Scope_Var{name = name, type_ = type_}, true
}

// Analyze nodes to find which scope variables are referenced
analyze_captures :: proc(g: ^Generator, nodes: []Node) -> []Scope_Var {
    captured: [dynamic]Scope_Var

    for sv in g.scope {
        if nodes_reference_var(nodes, sv.name) {
            append(&captured, sv)
        }
    }

    return captured[:]
}

// Check if any node references a variable by name
nodes_reference_var :: proc(nodes: []Node, var_name: string) -> bool {
    for node in nodes {
        if node_references_var(node, var_name) {
            return true
        }
    }
    return false
}

node_references_var :: proc(node: Node, var_name: string) -> bool {
    switch n in node {
    case Expr:
        if expr_contains_ident(n.value, var_name) do return true
    case Raw_Expr:
        if expr_contains_ident(n.value, var_name) do return true
    case Odin_Block:
        if expr_contains_ident(n.code, var_name) do return true
    case Element:
        for attr in n.attributes {
            if attr_references_var(attr, var_name) do return true
        }
        if nodes_reference_var(n.children, var_name) do return true
    case If_Node:
        if expr_contains_ident(n.cond, var_name) do return true
        if nodes_reference_var(n.then_, var_name) do return true
        for ei in n.else_ifs {
            if expr_contains_ident(ei.cond, var_name) do return true
            if nodes_reference_var(ei.then_, var_name) do return true
        }
        if nodes_reference_var(n.else_, var_name) do return true
    case For_Node:
        if expr_contains_ident(n.clause, var_name) do return true
        if nodes_reference_var(n.body, var_name) do return true
    case Switch_Node:
        if expr_contains_ident(n.expr, var_name) do return true
        for c in n.cases {
            if expr_contains_ident(c.expr, var_name) do return true
            if nodes_reference_var(c.body, var_name) do return true
        }
    case Call:
        if expr_contains_ident(n.expr, var_name) do return true
        if nodes_reference_var(n.default_slot, var_name) do return true
        for ns in n.named_slots {
            if nodes_reference_var(ns.body, var_name) do return true
        }
    case Text, Whitespace, Slot, Comment:
        // No expressions
    }
    return false
}

attr_references_var :: proc(attr: Attribute, var_name: string) -> bool {
    switch a in attr {
    case Expr_Attr:
        return expr_contains_ident(a.expr, var_name)
    case Bool_Expr_Attr:
        return expr_contains_ident(a.expr, var_name)
    case Cond_Attr:
        if expr_contains_ident(a.cond, var_name) do return true
        for ta in a.then_ {
            if attr_references_var(ta, var_name) do return true
        }
        for ea in a.else_ {
            if attr_references_var(ea, var_name) do return true
        }
    case Spread_Attr:
        return expr_contains_ident(a.expr, var_name)
    case Const_Attr, Bool_Attr:
        // No expressions
    }
    return false
}

// Check if an expression contains an identifier
// Simple approach: look for the identifier as a word boundary
expr_contains_ident :: proc(expr: string, ident: string) -> bool {
    if len(ident) == 0 || len(expr) == 0 {
        return false
    }

    idx := 0
    for idx <= len(expr) - len(ident) {
        found := strings.index(expr[idx:], ident)
        if found == -1 {
            return false
        }

        pos := idx + found
        // Check word boundaries
        before_ok := pos == 0 || !is_ident_char_gen(rune(expr[pos-1]))
        after_ok := pos + len(ident) >= len(expr) || !is_ident_char_gen(rune(expr[pos + len(ident)]))

        if before_ok && after_ok {
            return true
        }

        idx = pos + 1
    }
    return false
}

is_ident_char_gen :: proc(r: rune) -> bool {
    return (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_'
}

// Generate a unique ID: filehash_templatename_counter
gen_unique_id :: proc(g: ^Generator) -> string {
    id := g.uid_counter
    g.uid_counter += 1
    return fmt.tprintf("_%s_%s_%d", g.file_hash, g.current_template, id)
}

// Simple FNV-1a hash, returns 4 hex chars
hash_string :: proc(s: string) -> string {
    FNV_OFFSET :: 0x811c9dc5
    FNV_PRIME  :: 0x01000193

    hash: u32 = FNV_OFFSET
    for c in s {
        hash ~= u32(c)
        hash *= FNV_PRIME
    }

    // Return 4 hex chars (16 bits)
    return fmt.tprintf("%04x", hash & 0xFFFF)
}

// Node generation
emit_nodes :: proc(g: ^Generator, nodes: []Node) {
    for node in nodes {
        emit_node(g, node)
    }
}

emit_node :: proc(g: ^Generator, node: Node) {
    switch n in node {
    case Element:
        emit_element(g, n)
    case Text:
        emit_text(g, n)
    case Whitespace:
        // Skip whitespace in generated output
    case Expr:
        emit_expr(g, n)
    case Raw_Expr:
        emit_raw_expr(g, n)
    case Odin_Block:
        emit_odin_block(g, n)
    case If_Node:
        emit_if(g, n)
    case For_Node:
        emit_for(g, n)
    case Switch_Node:
        emit_switch(g, n)
    case Call:
        emit_call(g, n)
    case Slot:
        emit_slot(g, n)
    case Comment:
        // Omit HTML comments from output
    }
}

emit_element :: proc(g: ^Generator, e: Element) {
    // Open tag
    write_literal(g, "<")
    write_literal(g, e.tag)

    // Attributes
    emit_attributes(g, e.attributes)

    if e.self_close {
        write_literal(g, "/>")
        return
    }

    if e.void {
        write_literal(g, ">")
        return
    }

    write_literal(g, ">")

    // Children
    emit_nodes(g, e.children)

    // Close tag
    write_literal(g, "</")
    write_literal(g, e.tag)
    write_literal(g, ">")
}

emit_attributes :: proc(g: ^Generator, attrs: []Attribute) {
    for attr in attrs {
        switch a in attr {
        case Const_Attr:
            write_literal(g, " ")
            write_literal(g, a.key)
            write_literal(g, `="`)
            write_literal(g, escape_attr_value(a.value))
            write_literal(g, `"`)

        case Bool_Attr:
            write_literal(g, " ")
            write_literal(g, a.key)

        case Expr_Attr:
            write_literal(g, " ")
            write_literal(g, a.key)
            write_literal(g, `="`)
            flush_literal(g)
            gen_writeln(g, "templ.write_escaped(w, %s)", a.expr)
            write_literal(g, `"`)

        case Bool_Expr_Attr:
            flush_literal(g)
            gen_writeln(g, "if %s {{", a.expr)
            g.indent += 1
            write_literal(g, " ")
            write_literal(g, a.key)
            flush_literal(g)
            g.indent -= 1
            gen_writeln(g, "}}")

        case Cond_Attr:
            flush_literal(g)
            gen_writeln(g, "if %s {{", a.cond)
            g.indent += 1
            emit_attributes(g, a.then_)
            flush_literal(g)
            g.indent -= 1
            if len(a.else_) > 0 {
                gen_writeln(g, "}} else {{")
                g.indent += 1
                emit_attributes(g, a.else_)
                flush_literal(g)
                g.indent -= 1
            }
            gen_writeln(g, "}}")

        case Spread_Attr:
            flush_literal(g)
            // Strip leading .. from spread expression (template syntax sugar)
            expr := strings.trim_prefix(a.expr, "..")
            expr = strings.trim_space(expr)
            gen_writeln(g, "templ.write_attrs(w, %s)", expr)
        }
    }
}

emit_text :: proc(g: ^Generator, t: Text) {
    // Normalize whitespace - collapse runs of whitespace to single space
    text := normalize_whitespace(t.value)
    if text != "" {
        write_literal(g, text)
    }
}

emit_expr :: proc(g: ^Generator, e: Expr) {
    flush_literal(g)
    gen_writeln(g, "templ.write_escaped(w, %s)", e.value)
}

emit_raw_expr :: proc(g: ^Generator, e: Raw_Expr) {
    flush_literal(g)
    gen_writeln(g, "strings.write_string(w, %s)", e.value)
}

emit_odin_block :: proc(g: ^Generator, b: Odin_Block) {
    flush_literal(g)
    // Emit raw Odin code, preserving lines
    lines := strings.split_lines(b.code)
    for line in lines {
        trimmed := strings.trim_space(line)
        if trimmed != "" {
            gen_writeln(g, "%s", trimmed)
        }
    }
}

emit_if :: proc(g: ^Generator, n: If_Node) {
    flush_literal(g)

    gen_writeln(g, "if %s {{", n.cond)
    g.indent += 1
    emit_nodes(g, n.then_)
    flush_literal(g)
    g.indent -= 1

    for ei in n.else_ifs {
        gen_writeln(g, "}} else if %s {{", ei.cond)
        g.indent += 1
        emit_nodes(g, ei.then_)
        flush_literal(g)
        g.indent -= 1
    }

    if len(n.else_) > 0 {
        gen_writeln(g, "}} else {{")
        g.indent += 1
        emit_nodes(g, n.else_)
        flush_literal(g)
        g.indent -= 1
    }

    gen_writeln(g, "}}")
}

emit_for :: proc(g: ^Generator, n: For_Node) {
    flush_literal(g)

    // Parse for-loop variables and add to scope
    scope_start := len(g.scope)
    for_vars := parse_for_clause_vars_with_scope(n.clause, g.scope[:])
    for fv in for_vars {
        append(&g.scope, fv)
    }

    gen_writeln(g, "for %s {{", n.clause)
    g.indent += 1
    emit_nodes(g, n.body)
    flush_literal(g)
    g.indent -= 1
    gen_writeln(g, "}}")

    // Pop for-loop variables from scope
    for len(g.scope) > scope_start {
        pop(&g.scope)
    }
}

// Parse for-loop clause to extract iteration variables
// Handles: "item in items", "i, item in items", "i := 0; i < n; i += 1"
parse_for_clause_vars_with_scope :: proc(clause: string, scope: []Scope_Var) -> []Scope_Var {
    vars: [dynamic]Scope_Var

    // Check for "in" form: "item in items" or "i, item in items"
    in_idx := strings.index(clause, " in ")
    if in_idx != -1 {
        var_part := strings.trim_space(clause[:in_idx])
        collection_part := strings.trim_space(clause[in_idx+4:])

        // Try to find the element type from the collection in scope
        element_type := infer_element_type(collection_part, scope)

        // Split by comma for multiple variables
        // Odin: for value, index in collection (value first, index second!)
        var_names := strings.split(var_part, ",")
        for idx := 0; idx < len(var_names); idx += 1 {
            name := var_names[idx]
            trimmed := strings.trim_space(name)
            if trimmed != "" && trimmed != "_" {
                type_str: string
                if len(var_names) == 1 {
                    // Single var: element type
                    type_str = element_type
                } else if idx == 0 {
                    // First of two: value (element type)
                    type_str = element_type
                } else {
                    // Second of two: index
                    type_str = "int"
                }
                append(&vars, Scope_Var{name = trimmed, type_ = type_str})
            }
        }
        return vars[:]
    }

    // Check for C-style: "i := 0; ..."
    semi_idx := strings.index(clause, ";")
    if semi_idx != -1 {
        init_part := strings.trim_space(clause[:semi_idx])
        // Look for := declaration
        decl_idx := strings.index(init_part, ":=")
        if decl_idx != -1 {
            var_name := strings.trim_space(init_part[:decl_idx])
            if var_name != "" {
                append(&vars, Scope_Var{name = var_name, type_ = "int"})
            }
        }
    }

    return vars[:]
}

// Infer element type from a collection expression
// e.g., if "users" is "[]User" in scope, return "User"
infer_element_type :: proc(collection_expr: string, scope: []Scope_Var) -> string {
    // Simple case: collection is a direct identifier
    trimmed := strings.trim_space(collection_expr)

    for sv in scope {
        if sv.name == trimmed {
            // Found it - extract element type from slice/array type
            type_str := sv.type_
            // Handle []T, [N]T, [dynamic]T
            if strings.has_prefix(type_str, "[]") {
                return type_str[2:]
            }
            if strings.has_prefix(type_str, "[dynamic]") {
                return type_str[9:]
            }
            // [N]T - find the ]
            if len(type_str) > 0 && type_str[0] == '[' {
                bracket_end := strings.index(type_str, "]")
                if bracket_end != -1 && bracket_end + 1 < len(type_str) {
                    return type_str[bracket_end+1:]
                }
            }
        }
    }

    // Couldn't infer - use a placeholder that will likely cause a compile error
    // but at least shows what we tried
    return fmt.tprintf("/* element of %s */", trimmed)
}

emit_switch :: proc(g: ^Generator, n: Switch_Node) {
    flush_literal(g)

    gen_writeln(g, "switch %s {{", n.expr)
    for c in n.cases {
        if c.expr == "" {
            gen_writeln(g, "case:")
        } else {
            gen_writeln(g, "case %s:", c.expr)
        }
        g.indent += 1
        emit_nodes(g, c.body)
        flush_literal(g)
        g.indent -= 1
    }
    gen_writeln(g, "}}")
}

emit_call :: proc(g: ^Generator, c: Call) {
    flush_literal(g)

    // Parse the call expression to separate name from args
    expr := c.expr
    paren_idx := strings.index(expr, "(")

    has_default := len(c.default_slot) > 0
    has_named := len(c.named_slots) > 0

    if !has_default && !has_named {
        // Simple call without slots
        if paren_idx == -1 {
            gen_writeln(g, "%s(w)", expr)
        } else {
            name := expr[:paren_idx]
            args := expr[paren_idx+1:len(expr)-1]
            if strings.trim_space(args) == "" {
                gen_writeln(g, "%s(w)", name)
            } else {
                gen_writeln(g, "%s(w, %s)", name, args)
            }
        }
    } else {
        // Call with slots - analyze captures
        proc_name: string
        base_args: string

        if paren_idx == -1 {
            proc_name = expr
            base_args = ""
        } else {
            proc_name = expr[:paren_idx]
            base_args = strings.trim_space(expr[paren_idx+1:len(expr)-1])
        }

        // Collect all nodes from all slots to analyze captures
        all_slot_nodes: [dynamic]Node
        for node in c.default_slot {
            append(&all_slot_nodes, node)
        }
        for ns in c.named_slots {
            for node in ns.body {
                append(&all_slot_nodes, node)
            }
        }

        // Analyze what needs to be captured
        captures := analyze_captures(g, all_slot_nodes[:])

        // Generate unique suffix for this call's context
        uid := gen_unique_id(g)
        ctx_type := fmt.tprintf("Slot_Ctx%s", uid)
        ctx_var := fmt.tprintf("slot_ctx%s", uid)

        // If there are captures, generate context struct
        if len(captures) > 0 {
            // Generate context struct
            gen_writeln(g, "%s :: struct {{", ctx_type)
            g.indent += 1
            for cap in captures {
                gen_writeln(g, "%s: %s,", cap.name, cap.type_)
            }
            g.indent -= 1
            gen_writeln(g, "}}")

            // Initialize context
            gen_write(g, "%s := %s{{", ctx_var, ctx_type)
            first := true
            for cap in captures {
                if !first {
                    strings.write_string(&g.out, ", ")
                }
                strings.write_string(&g.out, fmt.tprintf("%s = %s", cap.name, cap.name))
                first = false
            }
            strings.write_string(&g.out, "}\n")
        }

        // Build the call with slot arguments
        gen_write(g, "%s(w", proc_name)

        if base_args != "" {
            strings.write_string(&g.out, ", ")
            strings.write_string(&g.out, base_args)
        }

        // Default slot
        if has_default {
            strings.write_string(&g.out, ", slot = proc(w: ^strings.Builder, data: rawptr) {\n")
            g.indent += 1
            // Unpack captures
            if len(captures) > 0 {
                gen_writeln(g, "ctx := (^%s)(data)^", ctx_type)
                for cap in captures {
                    gen_writeln(g, "%s := ctx.%s", cap.name, cap.name)
                }
            }
            emit_nodes(g, c.default_slot)
            flush_literal(g)
            g.indent -= 1
            gen_write(g, "}}")
            if len(captures) > 0 {
                strings.write_string(&g.out, fmt.tprintf(", slot_data = &%s", ctx_var))
            }
        }

        // Named slots
        for ns in c.named_slots {
            strings.write_string(&g.out, fmt.tprintf(", slot_%s = proc(w: ^strings.Builder, data: rawptr) {{\n", ns.name))
            g.indent += 1
            // Unpack captures
            if len(captures) > 0 {
                gen_writeln(g, "ctx := (^%s)(data)^", ctx_type)
                for cap in captures {
                    gen_writeln(g, "%s := ctx.%s", cap.name, cap.name)
                }
            }
            emit_nodes(g, ns.body)
            flush_literal(g)
            g.indent -= 1
            gen_write(g, "}}")
            if len(captures) > 0 {
                strings.write_string(&g.out, fmt.tprintf(", slot_%s_data = &%s", ns.name, ctx_var))
            }
        }

        strings.write_string(&g.out, ")\n")
    }
}

emit_slot :: proc(g: ^Generator, s: Slot) {
    flush_literal(g)
    if name, ok := s.name.?; ok {
        // Named slot - pass data pointer
        gen_writeln(g, "if slot_%s != nil {{ slot_%s(w, slot_%s_data) }}", name, name, name)
    } else {
        // Default slot - pass data pointer
        gen_writeln(g, "if slot != nil {{ slot(w, slot_data) }}")
    }
}

// CSS component generation
emit_css :: proc(g: ^Generator, css: CSS_Segment) {
    params := extract_params(css.params)

    // CSS components return a class name
    if params == "" {
        gen_writeln(g, "%s :: proc() -> string {{", css.name)
    } else {
        gen_writeln(g, "%s :: proc(%s) -> string {{", css.name, params)
    }

    g.indent += 1
    gen_writeln(g, `return "%s"`, css.name)
    g.indent -= 1
    gen_writeln(g, "}}")
    gen_writeln(g, "")

    // Also emit the CSS itself as a constant
    // Use escaped regular string if body contains backticks, otherwise raw string
    body := strings.trim_space(css.body)
    if strings.contains(body, "`") {
        full_css := strings.concatenate({".", css.name, " { ", body, " }"})
        escaped := escape_string_literal(full_css)
        gen_writeln(g, `%s_css :: "%s"`, css.name, escaped)
    } else {
        gen_writeln(g, "%s_css :: `.%s {{ %s }}`", css.name, css.name, body)
    }
    gen_writeln(g, "")
}

// Script template generation
emit_script :: proc(g: ^Generator, script: Script_Segment) {
    params := extract_params(script.params)

    if params == "" {
        gen_writeln(g, "%s :: proc() -> string {{", script.name)
    } else {
        gen_writeln(g, "%s :: proc(%s) -> string {{", script.name, params)
    }

    g.indent += 1
    gen_writeln(g, `return "%s()"`, script.name)
    g.indent -= 1
    gen_writeln(g, "}}")
    gen_writeln(g, "")

    // Use escaped regular string if body contains backticks, otherwise raw string
    body := strings.trim_space(script.body)
    if strings.contains(body, "`") {
        full_js := strings.concatenate({"function ", script.name, "() { ", body, " }"})
        escaped := escape_string_literal(full_js)
        gen_writeln(g, `%s_js :: "%s"`, script.name, escaped)
    } else {
        gen_writeln(g, "%s_js :: `function %s() {{ %s }}`", script.name, script.name, body)
    }
    gen_writeln(g, "")
}

// Literal batching
write_literal :: proc(g: ^Generator, s: string) {
    strings.write_string(&g.literal_buf, s)
}

flush_literal :: proc(g: ^Generator) {
    lit := strings.to_string(g.literal_buf)
    if len(lit) > 0 {
        escaped := escape_string_literal(lit)
        gen_writeln(g, `strings.write_string(w, "%s")`, escaped)
        strings.builder_reset(&g.literal_buf)
    }
}

// Helper procedures
gen_write :: proc(g: ^Generator, format: string, args: ..any) {
    for _ in 0..<g.indent {
        strings.write_string(&g.out, "\t")
    }
    strings.write_string(&g.out, fmt.tprintf(format, ..args))
}

gen_writeln :: proc(g: ^Generator, format: string, args: ..any) {
    gen_write(g, format, ..args)
    strings.write_string(&g.out, "\n")
}

// String escaping
escape_string_literal :: proc(s: string) -> string {
    b: strings.Builder
    strings.builder_init(&b)

    for r in s {
        switch r {
        case '\\':
            strings.write_string(&b, "\\\\")
        case '"':
            strings.write_string(&b, "\\\"")
        case '\n':
            strings.write_string(&b, "\\n")
        case '\r':
            strings.write_string(&b, "\\r")
        case '\t':
            strings.write_string(&b, "\\t")
        case:
            strings.write_rune(&b, r)
        }
    }

    return strings.to_string(b)
}

escape_attr_value :: proc(s: string) -> string {
    b: strings.Builder
    strings.builder_init(&b)

    for r in s {
        switch r {
        case '&':
            strings.write_string(&b, "&amp;")
        case '<':
            strings.write_string(&b, "&lt;")
        case '>':
            strings.write_string(&b, "&gt;")
        case '"':
            strings.write_string(&b, "&quot;")
        case:
            strings.write_rune(&b, r)
        }
    }

    return strings.to_string(b)
}

// Normalize whitespace - collapse runs to single space
normalize_whitespace :: proc(s: string) -> string {
    b: strings.Builder
    strings.builder_init(&b)

    in_whitespace := false
    for r in s {
        if is_whitespace(r) {
            if !in_whitespace {
                strings.write_rune(&b, ' ')
                in_whitespace = true
            }
        } else {
            strings.write_rune(&b, r)
            in_whitespace = false
        }
    }

    return strings.to_string(b)
}
